media: public/img

content:
  - name: about
    label: About Page
    type: file
    path: content/about/index.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: homepage
    label: Homepage
    type: file
    path: content/index.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: body, label: Main Content, type: rich-text }